// Copies the launchpad ABIs from Foundry's out/ into the site (committed, so the site builds without Foundry).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const out = new URL('../contracts/out/', import.meta.url);
const dest = new URL('../../site/src/launch/abi/', import.meta.url);
mkdirSync(dest, { recursive: true });
for (const name of ['BunkerLaunchpad', 'BunkerLaunchToken']) {
  const { abi } = JSON.parse(readFileSync(new URL(`${name}.sol/${name}.json`, out), 'utf8'));
  writeFileSync(new URL(`${name}.ts`, dest), `// generated by launchpad/scripts/export-abi.mjs — do not edit\nexport default ${JSON.stringify(abi, null, 1)} as const;\n`);
  console.log(name, abi.length, 'entries');
}
