// generated by launchpad/scripts/export-abi.mjs — do not edit
export default [
 {
  "type": "constructor",
  "inputs": [
   {
    "name": "poolManager_",
    "type": "address",
    "internalType": "contract IPoolManager"
   },
   {
    "name": "vault_",
    "type": "address",
    "internalType": "contract IBunkerVault"
   },
   {
    "name": "platform_",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "startSqrtPriceX96_",
    "type": "uint160",
    "internalType": "uint160"
   },
   {
    "name": "tickUpper_",
    "type": "int24",
    "internalType": "int24"
   },
   {
    "name": "liquidity_",
    "type": "uint128",
    "internalType": "uint128"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "receive",
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "CREATOR_SHARE_BPS",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "FEE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint24",
    "internalType": "uint24"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "FEE_TAG",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "LAUNCH_TAG",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_IMAGE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_META",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_NAME",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_SYMBOL",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "TICK_LOWER",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "int24",
    "internalType": "int24"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "TICK_SPACING",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "int24",
    "internalType": "int24"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "allCoins",
  "inputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "beforeInitialize",
  "inputs": [
   {
    "name": "sender",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct PoolKey",
    "components": [
     {
      "name": "currency0",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "currency1",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "fee",
      "type": "uint24",
      "internalType": "uint24"
     },
     {
      "name": "tickSpacing",
      "type": "int24",
      "internalType": "int24"
     },
     {
      "name": "hooks",
      "type": "address",
      "internalType": "address"
     }
    ]
   },
   {
    "name": "",
    "type": "uint160",
    "internalType": "uint160"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes4",
    "internalType": "bytes4"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "buy",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "minOut",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "to",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "deadline",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "out",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "claim",
  "inputs": [
   {
    "name": "to",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "claimableETH",
  "inputs": [
   {
    "name": "to",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "coins",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "identity",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "creator",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "leaf",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "launchedAt",
    "type": "uint64",
    "internalType": "uint64"
   },
   {
    "name": "feeTo",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "launchBlock",
    "type": "uint64",
    "internalType": "uint64"
   },
   {
    "name": "feeVault",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "coinsCount",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "coinsSlice",
  "inputs": [
   {
    "name": "from",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "count",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "out",
    "type": "address[]",
    "internalType": "address[]"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "collect",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "eth",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "tokens",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "feeDigest",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "identity",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "leaf",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "feeTo",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "feeVault",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "flushVault",
  "inputs": [
   {
    "name": "vaultId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "currency",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "identities",
  "inputs": [
   {
    "name": "identity",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "firstSeen",
    "type": "uint64",
    "internalType": "uint64"
   },
   {
    "name": "launches",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "identityOf",
  "inputs": [
   {
    "name": "seed",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "root",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "pure"
 },
 {
  "type": "function",
  "name": "isLeafUsed",
  "inputs": [
   {
    "name": "identity",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "leaf",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "launch",
  "inputs": [
   {
    "name": "p",
    "type": "tuple",
    "internalType": "struct BunkerLaunchpad.LaunchParams",
    "components": [
     {
      "name": "name",
      "type": "string",
      "internalType": "string"
     },
     {
      "name": "symbol",
      "type": "string",
      "internalType": "string"
     },
     {
      "name": "meta",
      "type": "string",
      "internalType": "string"
     },
     {
      "name": "image",
      "type": "bytes",
      "internalType": "bytes"
     },
     {
      "name": "devTo",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "devVault",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "feeTo",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "feeVault",
      "type": "bytes32",
      "internalType": "bytes32"
     }
    ]
   },
   {
    "name": "s",
    "type": "tuple",
    "internalType": "struct BunkerLaunchpad.PQSig",
    "components": [
     {
      "name": "seed",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "root",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "leaf",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "wots",
      "type": "bytes32[67]",
      "internalType": "bytes32[67]"
     },
     {
      "name": "auth",
      "type": "bytes32[10]",
      "internalType": "bytes32[10]"
     }
    ]
   }
  ],
  "outputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "payable"
 },
 {
  "type": "function",
  "name": "launchDigest",
  "inputs": [
   {
    "name": "identity",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "leaf",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "creator",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "devBuy",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "p",
    "type": "tuple",
    "internalType": "struct BunkerLaunchpad.LaunchParams",
    "components": [
     {
      "name": "name",
      "type": "string",
      "internalType": "string"
     },
     {
      "name": "symbol",
      "type": "string",
      "internalType": "string"
     },
     {
      "name": "meta",
      "type": "string",
      "internalType": "string"
     },
     {
      "name": "image",
      "type": "bytes",
      "internalType": "bytes"
     },
     {
      "name": "devTo",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "devVault",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "feeTo",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "feeVault",
      "type": "bytes32",
      "internalType": "bytes32"
     }
    ]
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "leafBitmap",
  "inputs": [
   {
    "name": "identity",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "words",
    "type": "uint256[4]",
    "internalType": "uint256[4]"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "liquidity",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint128",
    "internalType": "uint128"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pendingVault",
  "inputs": [
   {
    "name": "vaultId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "currency",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "platform",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "poolId",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "poolKey",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct PoolKey",
    "components": [
     {
      "name": "currency0",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "currency1",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "fee",
      "type": "uint24",
      "internalType": "uint24"
     },
     {
      "name": "tickSpacing",
      "type": "int24",
      "internalType": "int24"
     },
     {
      "name": "hooks",
      "type": "address",
      "internalType": "address"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "poolManager",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "contract IPoolManager"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "sell",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "amountIn",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "minOut",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "to",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "deadline",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "out",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setFeeTo",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "feeTo",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "feeVault",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "s",
    "type": "tuple",
    "internalType": "struct BunkerLaunchpad.PQSig",
    "components": [
     {
      "name": "seed",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "root",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "leaf",
      "type": "uint32",
      "internalType": "uint32"
     },
     {
      "name": "wots",
      "type": "bytes32[67]",
      "internalType": "bytes32[67]"
     },
     {
      "name": "auth",
      "type": "bytes32[10]",
      "internalType": "bytes32[10]"
     }
    ]
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setPlatform",
  "inputs": [
   {
    "name": "platform_",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "startSqrtPriceX96",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint160",
    "internalType": "uint160"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "tickUpper",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "int24",
    "internalType": "int24"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "tokenAddress",
  "inputs": [
   {
    "name": "identity",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "leaf",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "name",
    "type": "string",
    "internalType": "string"
   },
   {
    "name": "symbol",
    "type": "string",
    "internalType": "string"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "unlockCallback",
  "inputs": [
   {
    "name": "data",
    "type": "bytes",
    "internalType": "bytes"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes",
    "internalType": "bytes"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "usedLeaves",
  "inputs": [
   {
    "name": "identity",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "word",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "bits",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "vault",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "contract IBunkerVault"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "event",
  "name": "Attested",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "digest",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   },
   {
    "name": "seed",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   },
   {
    "name": "root",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   },
   {
    "name": "leaf",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   },
   {
    "name": "wots",
    "type": "bytes32[67]",
    "indexed": false,
    "internalType": "bytes32[67]"
   },
   {
    "name": "auth",
    "type": "bytes32[10]",
    "indexed": false,
    "internalType": "bytes32[10]"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Claimed",
  "inputs": [
   {
    "name": "to",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Collected",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "eth",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "tokens",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "creatorEth",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "creatorTokens",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Credited",
  "inputs": [
   {
    "name": "to",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "FeeToChanged",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "feeTo",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   },
   {
    "name": "feeVault",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   },
   {
    "name": "leaf",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "IdentitySeen",
  "inputs": [
   {
    "name": "identity",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "seed",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   },
   {
    "name": "root",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Image",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "image",
    "type": "bytes",
    "indexed": false,
    "internalType": "bytes"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Launched",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "identity",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "creator",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "leaf",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   },
   {
    "name": "name",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   },
   {
    "name": "symbol",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   },
   {
    "name": "meta",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   },
   {
    "name": "devBuy",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "devTokens",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "Payees",
  "inputs": [
   {
    "name": "token",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "devTo",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   },
   {
    "name": "devVault",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   },
   {
    "name": "feeTo",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   },
   {
    "name": "feeVault",
    "type": "bytes32",
    "indexed": false,
    "internalType": "bytes32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PlatformChanged",
  "inputs": [
   {
    "name": "platform",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "VaultPending",
  "inputs": [
   {
    "name": "vaultId",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "currency",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "amount",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "error",
  "name": "Locked",
  "inputs": []
 }
] as const;
